##
# Copyright 2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#  http://aws.amazon.com/apache2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.
##

require "rspec/core/rake_task"

desc "Run unit tests"
RSpec::Core::RakeTask.new(:unit_tests) do |spec|
  spec.rspec_opts = ['--color', '--format nested', '--profile']
  spec.pattern = 'spec/**/unit/*.rb'
end

desc "Run integration tests"
RSpec::Core::RakeTask.new(:integration_tests) do |spec|
  spec.rspec_opts = ['--color', '--format nested', '--profile']
  spec.pattern = 'spec/**/integration/*.rb'
end

desc "Run all tests"
RSpec::Core::RakeTask.new(:all_tests) do |spec|
  spec.rspec_opts = ['--color', '--format nested', '--profile']
  spec.pattern = 'spec/**/*.rb'
end

task :test => :all_tests

